[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = true

# Flow EVM Testnet Configuration
[rpc_endpoints]
flow_testnet = "https://testnet.evm.nodes.onflow.org"

[etherscan]
flow_testnet = { key = "${FLOWSCAN_API_KEY}", url = "https://evm-testnet.flowscan.io/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
